import type { Metadata } from "next";
import { Fira_Sans, Poppins, Roboto } from "next/font/google";
import Providers from "./Providers";
import "./globals.css";

export const metadata: Metadata = {
  title: "SkyBridge",
  description: "Generated by create next app",
};

const fontFiraSans = Fira_Sans({
  variable: "--font-fira-sans",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const fontPoppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
})

const FontRoboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
})

export default function RootLayout({children}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${fontPoppins.className} ${fontFiraSans.className} ${FontRoboto.className} antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
